version: '3.4'
services:
    db:
        image: report
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: report
        ports:
          - "3309:3309"
        networks:
          - fraude-networks
    transaction-reporties:
        build:
            context: .
            dockerfile: Dockerfile
        image: transaction-reporties:latest
        depends_on:
            - "db"        
        ports:
            - 8085:8085
        networks:
            - transaction-networks          
networks:
    fraude-networks:
        driver: bridge