version: '3.4'
services:
    db:
        image: fraude
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: fraude
        ports:
          - "3306:3306"
        networks:
          - transaction-networks
    transaction-fraude-cartao-credito:
        build:
            context: .
            dockerfile: Dockerfile
        image: transaction-fraude-cartao-credito:latest
        depends_on:
            - "db"
        ports:
            - 8082:8082
        networks:
            - transaction-networks
networks:
    transaction-networks:
        driver: bridge