server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/viniciusmmartinez/deliverys-config