version: '3.4'
services:
    db:
        image: auth
        command: mysqld --default-authentication-plugin=mysql_native_password
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DATABASE: auth
        ports:
          - "3308:3308"
        networks:
          - fraude-networks
networks:
    fraude-networks:
        driver: bridge